.PHONY: all

all:
	sudo mkdir -p /usr/local/share/lua/ && \
	sudo ln -sf /usr/share/lua/5.3 /usr/local/share/lua/5.1 && \
	mkdir -p  ~/.config/Renoise/V3.4.2/Scripts/dawdsl && \
	cp -f src/TestPad.lua ~/.config/Renoise/V3.4.2/Scripts/TestPad.lua && \
	cp -f src/TestPad.json ~/.config/Renoise/V3.4.2/Scripts/dawdsl/TestPad.json